# Generated by Django 5.1 on 2024-10-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=60, unique=True)),
                ('contrasena', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
