# Generated by Django 5.1 on 2024-11-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarioApp', '0002_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
