# Generated by Django 5.1 on 2024-11-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarioApp', '0003_evento_correo_alter_evento_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='correo',
        ),
        migrations.AlterField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
