# Generated by Django 5.1 on 2024-11-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarioApp', '0006_remove_evento_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
